added flipDirection/flipHour settings, stopname and filterDirection fix
edward-shen/MMM-MBTA pull request #16
Opened 2018-11-24 04:07 UTC by gmichaela

added the filterDirection fix, upon doing so, realized I care more about one direction in the morning and a different direction in the afternoon -- added a few more config flags, if flipDirection is set to true it will switch the direction at noon, if you want an hour other than noon as your flip time -- override with flipHour.

few other minor edits/fixes also included.

2018-11-24 05:07 UTC, edward-shen requested changes
Looks like a great PR! I just have some minor requests and then it looks good!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +
Please remove trailing whitespace.
```suggestion

```

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +        updateInterval: 30, // In seconds
Any particular reason for the change?

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +        directionFlipped: false
For all these values, can you please update the readme with these flags? Following what's been done is good enough!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +            descCell.innerHTML = "Nothing coming soon";
Missing a period or a "..."

```suggestion
            descCell.innerHTML = "Nothing coming soon...";
```

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +            url += "&page[limit]=" + (this.config.maxEntries + 10) + '"';
Nice catch!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +            url += "&filter[max_time]=" + moment().add(5, 'h').format("HH:mm");
Any particular reason for this change? if you want to keep it at five, make sure to update the comment on line 452!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +        {
Please be consistent with the already existing guide. This should be

```
if (...) {
  ...
}
```

Thanks!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +        {
There are a few more in the follow code too!

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +            this.stationData = this.stationData.filter(obj => (obj.directionId == this.filterDirection));
Double equals is discouraged. This should be `===`.
```suggestion
            this.stationData = this.stationData.filter((obj) => obj.directionId === this.filterDirection);
```

2018-11-24 05:07 UTC, edward-shen commented on MMM-MBTA.js
> +
Please leave only one blank lines between one thing and the next.

2018-11-24 05:10 UTC, edward-shen commented
Fixes #5.

2018-11-24 05:26 UTC, gmichaela commented on MMM-MBTA.js
> +            url += "&filter[max_time]=" + moment().add(5, 'h').format("HH:mm");
I wanted to see more trips coming, commuter rails don't have too many options in the 3 hour window sometimes...   the predictedTimes api doesnt seem to return too far in advance either, so I was just experimenting with adding more time here -- I saw that you truncated the list at the end anyway...

2018-11-24 16:50 UTC, edward-shen commented on MMM-MBTA.js
> +            url += "&filter[max_time]=" + moment().add(5, 'h').format("HH:mm");
Alright, that's understandable! Just update the comment and you should be all set for this part!

2018-11-27 02:35 UTC, gmichaela commented
Made some more edits -- updated readme, fixed a filter direction bug.

2018-11-27 03:23 UTC, gmichaela commented on MMM-MBTA.js
> +            this.stationData = this.stationData.filter(obj => (obj.directionId == this.filterDirection));
ended up it should have been =

2018-11-27 03:43 UTC, edward-shen approved these changes
Please accept the suggestions and your PR will be merged! 

Thanks for working with me on this, I really appreciate the PR!

2018-11-27 03:43 UTC, edward-shen commented on readme.md
> +`flipHour`| When set with flipDirection the time of day you want to flip direction to override 12 noon<br/>**Expected Value type:** `int`.
```suggestion
`flipHour`| Specifies the hour to flip the direction, if `flipDirection` is equal to `true`. Default value is 12.**Expected Value type:** `int`.
```

2018-11-27 03:43 UTC, edward-shen commented on readme.md
> +`flipDirection`| Set to true, it will flip direction filter flag, ie: Inbound in the AM Outbound in PM<br/>**Expected Value type:** `boolean`.
```suggestion
`flipDirection`| When set to `true`, MMM-MBTA will the flip the direction filter for incoming vehicles at the station, i.e. Inbound in the AM and Outbound in PM<br/>**Expected Value type:** `boolean`.
```

2018-11-27 04:28 UTC, gmichaela commented on readme.md
> +`flipHour`| When set with flipDirection the time of day you want to flip direction to override 12 noon<br/>**Expected Value type:** `int`.
Adding Outbound etc wouldn't hurt either...

2018-11-27 07:17 UTC, merged

2018-11-27 07:17 UTC, edward-shen commented
Merged! :tada: